---
title: "Simulation example: fixed threshold"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulation example: fixed threshold}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
In this vignette, we will assess the performance of the elastic combining estimator with a fixed threshold $c_\gamma$. All data generating distributions are the same as in [here](sim_psi011_111.html). The following code reproduces the simulation studies in Yang et al., (2022), Section S4.5 and the plot in Figure S2.
```{r include=FALSE}
library(ElasticIntegrative)
m <- 2000 # size for RWE
niter <- 500 # number of replication
thres.psi  <-  sqrt(log(m)) # threshold for ACI psi
alltlocalpar <- c(2,1,round((seq(0.8,0,length.out=8)),2))
```
```{r eval=FALSE, include=TRUE}
# psi = c(0, 0, 0)
elastic_psi000_fixed_lists <- lapply(alltlocalpar, function(tlocalpar)
  {
  elastic_list <- sapply(1:niter, function(seed)
  {
    Data.list <- GenData(beta0 = c(0, 1, 1, 1), # for the mu0 function
                         psi0 = c(0, 0, 0), # for the contrast function
                         n = 1e5, mean.x = 1,  # setup for the finite population
                         n.t = NULL, # for the RCT, use the default sample size
                         m = m, tlocalpar = tlocalpar, # for the RWE
                         seed = seed)
    elasticHTE(Data.list$RT, # RCT
               Data.list$RW, # RWE
               thres.psi = thres.psi,
               fixed = TRUE # adaptive selection strategy
               )
  })
  class(elastic_list) <- 'res'
  elastic_list
})
# psi = c(0, 1, 1)
elastic_psi011_fixed_lists <- lapply(alltlocalpar, function(tlocalpar)
  {
  elastic_list <- sapply(1:niter, function(seed)
  {
    Data.list <- GenData(beta0 = c(0, 1, 1, 1), # for the mu0 function
                         psi0 = c(0, 1, 1), # for the contrast function
                         n = 1e5, mean.x = 1,  # setup for the finite population
                         n.t = NULL, # for the RCT, use the default sample size
                         m = m, tlocalpar = tlocalpar, # for the RWE
                         seed = seed)
    elasticHTE(Data.list$RT, # RCT
               Data.list$RW, # RWE
               thres.psi = thres.psi,
               fixed = TRUE # adaptive selection strategy
               )
  })
  class(elastic_list) <- 'res'
  elastic_list
})
```
At last, we reproduce the summary results in Yang et al., (2022), Figure S2 as follow.
```{r include=FALSE}
library(dplyr)
library(latex2exp)
library(ggplot2)
library(tidyr)
# the raw data is generated by the Rcode in the data-raw folder
# tabulate the results for psi 000
psi <- c(0, 0, 0)
sim_results_psi00_fixed <-
  sapply(elastic_psi000_fixed_lists,
         function(res)summary(res, psi = psi))
est.mat.psi00.fixed <- do.call(rbind, sim_results_psi00_fixed[1,])
ve.mat.psi00.fixed <- do.call(rbind, sim_results_psi00_fixed[2,])
row.names(est.mat.psi00.fixed) <- row.names(ve.mat.psi00.fixed) <- 
  rev(alltlocalpar)
bias.psi0.fixed <- est.mat.psi00.fixed-0
variance.psi0.fixed <- ve.mat.psi00.fixed

# tabulate the results for psi 011
psi <- c(0, 1, 1)
sim_results_psi11_fixed <-
  sapply(elastic_psi011_fixed_lists, function(res)summary(res, psi = psi))
est.mat.psi11.fixed <- do.call(rbind, sim_results_psi11_fixed[1,])
ve.mat.psi11.fixed <- do.call(rbind, sim_results_psi11_fixed[2,])
row.names(est.mat.psi11.fixed) <- row.names(ve.mat.psi11.fixed) <- 
  rev(alltlocalpar)
bias.psi1.fixed <- est.mat.psi11.fixed-1
variance.psi1.fixed <- ve.mat.psi11.fixed
```
```{r echo=FALSE, fig.height=5, fig.width=6.5, fig.align = 'center'}
outputs <- list(bias.psi0 = bias.psi0.fixed, bias.psi1 = bias.psi1.fixed,
                variance.psi0 = variance.psi0.fixed, variance.psi1 = variance.psi1.fixed)
class(outputs) <- 'res'
# plot the bias, variance and mean squared error
plot(x = outputs, AIPW = F)
```
